const ENV_MISSING_BASE = (envName: string) =>
	`환경변수 ${envName}가 설정되지 않았습니다`;

export const ERROR_MESSAGE = {
	ENV_MISSING: {
		TTB_KEY: ENV_MISSING_BASE('TTB_KEY'),
		ALADIN_BASE_API_URL: ENV_MISSING_BASE('ALADIN_BASE_API_URL'),
		ALADIN_LIST_API_URL: ENV_MISSING_BASE('ALADIN_LIST_API_URL'),
	},
};
